### Feature Statistical Descriptions

In [1]:
# imports
import pandas as pd
import psycopg2
import config as c

# import for multiple output per cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# connection to database
connection = psycopg2.connect(
    host = c.host,
    port = c.port,
    user = c.user,
    password = c.password,
    database = c.database
    )
cursor=connection.cursor()

In [10]:
# SQL query
data_sql = """
SELECT *
FROM final_dataset;
"""

# load in tables as dataframes
data_df = pd.read_sql(data_sql, con=connection)

In [11]:
# drop coulmns
data_df.drop(['GUID',
              'Name',
              'HallofFameClass',
              'YearDrafted',
              'TO_YEAR',
              'Years_Played',
              'HOF_Elgibility_Year',
              'Team',
              'College',
              'GP',
              'MIN',
              'idPlayer',
              'BIRTHDATE',
              'POSITION',
              'AGE_ROOKIE_SEASON',
              'Draft_Decade',
              'numBallotsBeforeInduct'], 
             axis=1, inplace=True)
data_df.head()

,Pick,PTS,FGM,FGA,FG%,3P_Made,3PA,3P%,FTM,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF,numberRound
0,21,6.3,2.8,5.2,53.3,0.0,0.1,0.0,0.8,1.3,62.5,1.7,3.5,5.2,0.4,0.5,0.5,1.0,9.0,1
1,26,5.6,1.9,6.0,32.3,1.1,3.6,30.1,0.7,0.8,86.1,0.5,1.6,2.0,0.5,0.5,0.3,0.5,4.3,1
2,32,7.9,2.8,7.0,39.6,0.7,2.4,28.7,1.6,2.1,75.2,1.0,2.2,3.2,1.2,0.7,1.1,1.7,7.6,2
3,34,5.4,1.9,5.5,35.5,0.6,2.2,26.2,0.9,1.2,75.0,0.6,1.9,2.5,0.9,0.6,0.3,1.0,4.8,2
4,60,3.7,1.5,3.3,44.9,0.0,0.3,13.3,0.6,1.1,57.4,0.9,2.0,2.9,0.3,0.2,0.4,0.4,4.8,2

In [12]:
data_df.describe()

,Pick,PTS,FGM,FGA,FG%,3P_Made,3PA,3P%,FTM,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF,numberRound
count,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000
mean,68.579293,6.545357,2.539934,5.658094,44.239359,0.208546,0.660559,18.093755,1.257929,1.780608,69.782251,1.018324,1.957354,2.976828,1.460887,0.590058,0.376335,1.178472,7.124158,3.487264
std,77.888978,4.277932,1.663170,3.497791,6.095721,0.358853,0.990077,16.698836,0.960942,1.302005,10.649408,0.776718,1.351010,2.057817,1.398089,0.402612,0.475725,0.703046,4.580004,3.698112
min,1.000000,0.700000,0.300000,0.800000,20.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,0.200000,0.000000,0.000000,0.000000,0.100000,0.200000,1.000000
25%,14.000000,3.500000,1.400000,3.100000,40.400000,0.000000,0.000000,0.000000,0.600000,0.900000,64.200000,0.500000,1.000000,1.500000,0.500000,0.300000,0.100000,0.700000,3.700000,1.000000
50%,29.000000,5.200000,2.000000,4.600000,44.300000,0.000000,0.200000,20.000000,1.000000,1.400000,70.700000,0.800000,1.700000,2.400000,1.000000,0.500000,0.200000,1.000000,6.100000,2.000000
75%,165.000000,8.500000,3.300000,7.300000,48.000000,0.300000,0.900000,32.000000,1.600000,2.300000,77.100000,1.400000,2.500000,3.800000,1.900000,0.800000,0.500000,1.500000,9.400000,4.000000
max,200.000000,28.200000,10.200000,19.800000,73.700000,2.000000,6.500000,100.000000,7.700000,10.200000,100.000000,5.400000,9.600000,13.900000,10.600000,2.500000,5.000000,4.400000,30.600000,10.000000